### ISSUE TITLE
Possible further optimisation for `glob`

### ISSUE THREAD

**Issue by hdgarrood** [Deewiant/glob#15]
This has just occurred to me after working on the optimisation for `glob`: if given a pattern with one or more literal segments at the start, `globDir'` recurses and performs a `getDirectoryContents` at every level. Therefore, presumably we can reduce the amount of time spent in these calls if the `glob` function always uses `commonDirectory` first, since for any glob which has one or more literal segments at the beginning there's no point in enumerating anything else outside that `commonDirectory`? This change presumably would affect the list of unmatched files in cases where this list is returned, so presumably we can't make this optimisation in any function which does return a list of unmatched files. But `glob` isn't one of those, so making this change could potentially give `glob` a nice performance boost.

I'll look at this after #12.

**Comment by Deewiant** [comment]
Yes, good point. It makes sense to do this whenever we're not returning unmatched files.
