### ISSUE TITLE
Extra slashes appearing in `commonDirectory`

### ISSUE THREAD

**Issue by hdgarrood** [Deewiant/glob#18]
While working on #15 I noticed the following:

```haskell
> commonDirectory (compile "foo/*/*.hs")
("foo/",compile "*//*.hs")
```

I was expecting to get `("foo/",compile "*/*.hs")`. Is this a bug?

**Comment by Deewiant** [comment]
I'd say so, yes. :-)

`commonDirectory` seems to lack tests... I imagine that a trivial QuickCheck property along the lines of `\x -> let (a, b) = commonDirectory (compile x) in x == literal a <> b` would catch this.

**Comment by hdgarrood** [comment]
Great, okay, I'll take a crack at this one then.
