### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hdgarrood** [Deewiant/glob#21]
Do you think now might be a good time to publish a new release of this library? I'd appreciate it a lot if you were able to do that. I had a go at writing release notes for the things I've done over the last couple of days:

> Fix a bug where commonDirectory would add extra slashes to the returned Pattern.
>
> Add an isLiteral function for determining whether a Pattern is a literal file or directory path.
>
> Significant performance improvements for the globbing functions which do not return a list of unmatched files in addition to matched files.
>
> Add a new GlobOptions data type, which is like MatchOptions, except that it also accepts a Bool flag to control whether unmatched files should be returned.
>
> Modify globDir to only return matched files, in order to better match globDir1.
>
> Modify globDirWith to accept a GlobOptions rather than MatchOptions, and so that unmatched files are wrapped in a Maybe, in order to distinguish situations where there were no unmatched files vs where the user did not ask for a list of unmatched files to be collected.

**Comment by Deewiant** [comment]
I think I'd rather sort out #16 first. Fixing it will be a behavioural change so it'll also require a new major version anyway (in PVP terms; I still like to live in 0.x land :-)), and I don't think it'll be that much work.

But regardless, I'm afraid I'm too busy this weekend to do much more than respond to you when I get the chance, so it'll be at least a few days.

**Comment by hdgarrood** [comment]
Ok, that makes sense :) I'll see what I can do about #16 then.

**Comment by Deewiant** [comment]
Glob-0.9.0 is now up on Hackage.
