### ISSUE TITLE
Occasional failures of prop_commonDirectory

### ISSUE THREAD

**Issue by hdgarrood** [Deewiant/glob#23]
See the failing CI in #22.

The issue seems to be with cases where `[.]` appears somewhere other than at the beginning or directly after a path separator; the property is testing that the two patterns are equal, and they ought to behave the same for matching, but one has the `.` inside a `LongLiteral` constructor, and the other has it as an `ExtSeparator` constructor.

I think there are two possible ways to fix this. We could either modify `compile` so that any pair of patterns such as `"foo."` and `"foo[.]"` do come out the same, presumably by changing "implicit" dots, i.e. dots inside `LongLiteral` constructors, into "explicit" ones, i.e. ones inside `ExtSeparator` constructors, in all cases (unless this would cause `.` or `..` to match the pattern where they otherwise would not). Alternatively, we could modify the tests to account for this possible discrepancy while testing. I think the first option sounds simpler, and also would make the behaviour of `==` on Patterns a little more intuitive.

**Comment by hdgarrood** [comment]
Come to think of it I think it would be easier if we made a new Token constructor for `[.]`, as you suggested in https://github.com/Deewiant/glob/pull/19#discussion_r136691717

**Comment by Deewiant** [comment]
One option would also be to accept the state of affairs and modify the test to not assume more of the `Eq` instance than is actually guaranteed.

`optimizeCharRange` has this comment:

```hs
   -- [.] can be Literalized though, just don't make it into an ExtSeparator so
   --     that it doesn't match a leading dot
```

I think that idea could be tweaked a bit: we can turn it into an `ExtSeparator` when we know it's not in a leading position (start of pattern or after a path separator). I suppose this is what you meant by your first suggestion. But we could also do it the other way around and combine `ExtSeparators` with surrounding `Literals` to form `LongLiterals` whenever the `ExtSeparator` is not in a leading position. This would cut down on `Pattern` size and probably speed up matching a bit. The side effect of that is that the `Show` instance for `Token` would cause e.g. `compile "foo.bar"` to be shown as `compile "foo[.]bar"`, which is maybe a bit too unexpected for users...

**Comment by hdgarrood** [comment]
> One option would also be to accept the state of affairs and modify the test to not assume more of the Eq instance than is actually guaranteed.

This occurred to me, but I think even if we do this, we'll want to create some kind of normalising function which lets us compare Patterns for the purpose of this property anyway, in which case we might as well put that code inside the library as part of `optimize` so that users can benefit from it too?

**Comment by hdgarrood** [comment]
> But we could also do it the other way around and combine ExtSeparators with surrounding Literals to form LongLiterals whenever the ExtSeparator is not in a leading position. This would cut down on Pattern size and probably speed up matching a bit. The side effect of that is that the Show instance for Token would cause e.g. compile "foo.bar" to be shown as compile "foo[.]bar", which is maybe a bit too unexpected for users...

This sounds good to me, except for the fact that `show (compile "foo.bar")` would come out as `"compile "foo[.]bar"`, but maybe we could address that by adding an `ImplicitExtSeparator` constructor, only to be used when `[.]` appears at the start of a pattern or after a path separator? Then a dot in a `Literal` or `LongLiteral` could be shown as `.` rather than `[.]`.

**Comment by Deewiant** [comment]
> > One option would also be to accept the state of affairs and modify the test to not assume more of the Eq instance than is actually guaranteed.
>
> This occurred to me, but I think even if we do this, we'll want to create some kind of normalising function which lets us compare Patterns for the purpose of this property anyway, in which case we might as well put that code inside the library as part of optimize so that users can benefit from it too?

If done it nicely like that, then yes, sure. I was thinking more of mangling the property's input to avoid this kind of problem — some sort of destructive operation that has no business in `optimize`.

>  But we could also do it the other way around and combine ExtSeparators with surrounding Literals to form LongLiterals whenever the ExtSeparator is not in a leading position. This would cut down on Pattern size and probably speed up matching a bit. The side effect of that is that the Show instance for Token would cause e.g. compile "foo.bar" to be shown as compile "foo[.]bar", which is maybe a bit too unexpected for users...
>
> This sounds good to me, except for the fact that show (compile "foo.bar") would come out as "compile "foo[.]bar", but maybe we could address that by adding an ImplicitExtSeparator constructor, only to be used when [.] appears at the start of a pattern or after a path separator? Then a dot in a Literal or LongLiteral could be shown as . rather than [.].

Yes, if we can manage to make that work consistently then it should be fine like that.

Since `[.]` at the start of a pattern or after a path separator makes it impossible for the pattern to match, I'd go ahead and call it something like `Impossible` though (or e.g. `Unmatchable`, `Unreachable`, etc.). Then `[/]` could also be turned into that, and patterns containing that token optimized into just `[Impossible]`.

**Comment by hdgarrood** [comment]
Ah of course, thanks! I'll give that a try then.
