### ISSUE TITLE
Output of glob is not in lexicographic order

### ISSUE THREAD

**Issue by jbweston** [Deewiant/glob#27]
Not sure if this is a bug or expected behavior, but glob matches are returned in a (seemingly) arbitrary order.

I would expect the results to be in lexicographic order, so as to match the output of `ls` on the same glob.

### Steps to reproduce
+ Create some files
```shell
touch a b x
```

+ Install `Glob` version `0.9.2`

+ Match some globs
```haskell
λ> import System.FilePath.Glob
λ> glob "?"
["/tmp/glob-test/b","/tmp/glob-test/x","/tmp/glob-test/a"]
```

**Comment by Deewiant** [comment]
This is expected: `glob` returns the files in the same order as [`getDirectoryContents`](https://hackage.haskell.org/package/directory/docs/System-Directory.html#v:getDirectoryContents) produces them. Try `ls -U` ("do not sort; list entries in directory order") and you should see the same order. If you want to sort the results, you may do so yourself afterwards — that's what `ls` also does internally.

**Comment by jbweston** [comment]
Thanks for the clarification.
