### ISSUE TITLE
** has inconsistent behavior with hidden directories

### ISSUE THREAD

**Issue by tssund93** [Deewiant/glob#29]
`match (compile "haskell/sbu/**/dist/*") "haskell/sbu/.stack-work/dist/test"`
(trying to use `**` to match one level) returns `False` but
`match (compile "haskell/**/dist/*") "haskell/sbu/.stack-work/dist/test"`
(using `**` to match two levels) returns `True`.

Is this a bug or am I missing something about how globs work?

**Comment by tssund93** [comment]
Looked through the code and realized it's because of the hidden directory.  So never mind about that!  On the other hand, should the second snippet be returning `False` then?

**Comment by Deewiant** [comment]
Yes, the second result definitely looks like a bug. This is supposed to be what the `matchDotsImplicitly` option in `MatchOptions` controls.

**Comment by Deewiant** [comment]
Released as 0.10.0.
