### ISSUE TITLE
The documentation is a little squiffy

### ISSUE THREAD

**Issue by expipiplus1** [Deewiant/glob#6]
The text describing the character classes renders quite poorly on hackage here:
https://hackage.haskell.org/package/Glob-0.7.11/docs/System-FilePath-Glob.html#v:compile

**Comment by Deewiant** [comment]
Apparently Haddock started misrendering this somewhere between 2013 and 2014. Reported upstream: haskell/haddock#546

**Comment by Deewiant** [comment]
The upstream issue was closed already a year ago, I don't know why I forgot to update this. It looks correct again now: https://hackage.haskell.org/package/Glob-0.9.3/docs/System-FilePath-Glob.html#v:compile

**Comment by expipiplus1** [comment]
thanks!
